fix: local dependencies correct bump from release to prerelease
qiwi/multi-semantic-release pull request #34
Opened 2021-01-04 17:19 UTC by davikawasaki

Fixes bug #27. Tried to cover most of edge cases I've imagined, reusing code from semantic-release repository.

2021-01-04 17:47 UTC, antongolub commented
@davikawasaki,

Wow! Outstanding improvement! But I need some time to sober up and be ready for review (10-12 hours).

CC @oljekechoro, @pismenskiy

2021-01-04 17:56 UTC, davikawasaki commented
@antongolub np. Fixing the code complexity rn.

2021-01-05 08:22 UTC, antongolub requested changes

2021-01-05 08:22 UTC, antongolub commented on lib/utils.js
> +	if (!tags) tags = [];
How about "fail fast"?
```js
if (!tags) {
  return []
}
```

2021-01-05 08:22 UTC, antongolub commented on lib/utils.js
> +function getHighestLowest(version1, version2, type = 1) {
A bit confusing to me. Let's separate?
```js
const selectVersionBy = (predicate, version1, version2) => {

if (predicate && !version1 && !version2) {
   return predicate(version1, version2) ? version1 : version2
}

return version1 || version2
}

const getHighestVersion = selectVersionBy.bind(null, gt)
const getLowestVersion = selectVersionBy.bind(null, lt)
```

2021-01-05 10:13 UTC, davikawasaki commented on lib/updateDeps.js
> +	if (!tags || !tags.length) tags = getTags(pkg._branch || "master", { cwd: "." }, tagFilters);
No need. Removing it.

2021-01-05 10:31 UTC, antongolub approved these changes
@davikawasaki, 

LTGM. I'm going to merge. If everything is ok, once again I ask you to push these changes to the parent repo so that I don't have to "steal" your PR ))

2021-01-05 10:32 UTC, merged

2021-01-05 10:51 UTC, davikawasaki commented
@antongolub great. I'll just add a PR refactor to reduce code complexity in a bit.